# This workflow will run build and unit test on every PR raised.

name: "Format and Build IaC"

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      workingDirectory:
        description: "The directory where the Bicep files are located"
        type: string
        required: true
        default: ./env
      mainBicepFile:
        description: "The main Bicep file to build"
        type: string
        required: true
        default: ./env/main.bicep

jobs:
  format-bicep:
    name: Validate Bicep
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@main
      # - name: Format Bicep
      #   id: format-bicep
      #   run: |
      #     # Set the path to the root directory where you want to search for .bicep files
      #     $rootDirectory = "${{ inputs.workingDirectory }}"

      #     # Get a list of all .bicep files in the specified directory and its subdirectories
      #     $files = Get-ChildItem -Path $rootDirectory -Filter "*.bicep" -File -Recurse

      #     # Loop through the list of .bicep files and execute an Azure CLI command on each file
      #     foreach ($file in $files) {
      #         $bicepFilePath = $file.FullName
      #         $azCommand = "az bicep format -f $file"

      #         # Run the Azure CLI command
      #         Write-Host "Processing -> $file.Name"
      #         Invoke-Expression $azCommand
      #    }
      - name: print input
        run: Write-host "The value is ${{ inputs.workingDirectory }}"
      - name: Build Bicep
        id: build-bicep
        run: |
          mainFile=${{inputs.mainBicepFile}}
          echo "Building Bicep file: $mainFile"
          az bicep build -f $mainFile
