name: Deploy infrastructure

on:
  workflow_dispatch:
    inputs:
      bicepTemplatePath:
        description: "The path to the top-level bicep template, e.g. main.bicep"
        default: env/main.bicep
        type: string
      additionalBicepParameters:
        default: ""
        type: string
      # clientAffix:
      #   required: true
      #   type: string
      env:
        default: Sd
        type: string
      resourceGroup:
        type: string
        required: true
        default: "rg-accelerator-sd"
      resourceGroupLocation:
        type: string
        default: "eastus"
      variablesYamlPath:
        type: string
        default: "./pipelines/variables.yml"
      vmImage:
        type: string
        default: "ubuntu-latest"
      doesKeyVaultExist:
        type: boolean
        default: true
  workflow_call:
    # outputs:
    #   acrName:
    #     description: "Name of ACR"
    #     value: ${{ jobs.deploy-bicep.outputs.acrName }}

jobs:
  deploy-bicep:
    runs-on: ${{ inputs.vmImage }}
    defaults:
      run:
        shell: pwsh
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          # Credentials inherited from parent workflow
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set ENV values from YAML
        uses: dcarbone/yaml-to-env-action@v1.0.0
        with:
          debug: false
          yaml-file: '${{ inputs.variablesYamlPath }}'
          yq-version: '4.27.5'

      - run: |
          az account show
          az group create --name ${{ inputs.resourceGroup }} --location ${{ inputs.resourceGroupLocation }}

      - name: Deploy Bicep Template
        id: bicep-deploy
        run: |
          az --version
          az deployment group create `
            --resource-group ${{ inputs.resourceGroup }} `
            --name azuredeploy-$($env:GITHUB_RUN_ATTEMPT) `
            --template-file ${{ inputs.bicepTemplatePath }} `
            --parameters `
              clientAffix=$env:VARIABLES_CLIENTAFFIX `
              env=${{ inputs.env }} `
              projectAffix=$env:VARIABLES_PROJECTAFFIX `
              componentAffix=$env:VARIABLES_COMPONENTAFFIX `
              qualifyComponentAffix=true `
              sqlAdminLogin=${{ secrets.SQL_ADMIN_LOGIN }} `
              sqlAdminLoginPassword=${{ secrets.SQL_ADMIN_LOGIN_PASSWORD }} `
              doesKeyVaultExist=${{ inputs.doesKeyVaultExist }} `
              ${{ inputs.additionalBicepParameters }}

      - name: "Capture Bicep Outputs"
        id: bicep-outputs
        run: |
          $out = az deployment group show -g ${{ inputs.resourceGroup }} -n "azuredeploy-$($env:GITHUB_RUN_ATTEMPT)" | convertfrom-json | foreach properties | foreach outputs
          mkdir bicep-outputs
          if($out -ne $null)
          {
              $provisionOutputs = [PSCustomObject]@{}
              $out | Get-Member -MemberType NoteProperty | ForEach-Object {
                $name = $_.name
                $provisionOutputs | Add-Member -MemberType NoteProperty -Name $name -value $out.$name.value
                Write-Host "BICEP output key/value -> $($name): $($out.$name.value)"
                Set-Content -Path bicep-outputs/$($name) -Value $($out.$name.value)
                echo "$name=$($out.$name.value)" >> $GITHUB_OUTPUT
              }
          }
          else {
              Write-Host "BICEP outputs are null"
          }

      - name: "print outputs"
        run: |
          echo ${{ steps.bicep-outputs.outputs.namingPrefix }}

      - uses: actions/upload-artifact@v3
        with:
          name: bicep-outputs
          path: bicep-outputs/
